from .make_model import make_model
from .backbones.swin_transformer_uda import uda_swin_base_patch4_window7_224_TransReID, uda_swin_small_patch4_window7_224_TransReID
from .backbones.vit_pytorch_uda import uda_vit_small_patch16_224_TransReID
